const USERS = [
    { name: "Adriana Nascimento", password: "029560" },
    { name: "Adriene Jeane", password: "065783" },
    { name: "Allan Dourado", password: "012022", canCancelOthers: true },
    { name: "Jorge Neto", password: "042684" },
    { name: "Debora Vidal", password: "070747" },
    { name: "Juliana Von", password: "017900" },
    { name: "Karyanne Oliveira", password: "028530" },
    { name: "Luciana Lima", password: "036570", isAdmin: true },
    { name: "Marcus Vinicius", password: "086180", canCancelOthers: true },
    { name: "Adilline Bezerra", password: "026722" },
    { name: "Miriam Torres", password: "043906" },
    { name: "Patricia Furtado", password: "060866" },
    { name: "Paula Targino", password: "067005" },
    { name: "Raiza Brandão", password: "026038" },
    { name: "Tatiane Vasconcelos", password: "036507" },
    { name: "Vanessa Brito", password: "073841" },
    { name: "Vanessa Sobrinho", password: "060747" },
    { name: "Thais Freitas", password: "059531" },
    { name: "Mayara Souza", password: "032101" },
    { name: "Mikaelle Sousa", password: "044843" },
    { name: "Emerson Sousa", password: "624211" },
    { name: "Suprimentos", password: null },
    { name: "Treinamento", password: null },
    { name: "Controladoria", password: null },
    { name: "G&C", password: null },
    { name: "ADM Geral", password: null },
    { name: "TI", password: null },
    { name: "Qualidade", password: null },
    { name: "Estacio", password: null },
    { name: "Marketing", password: null }
];

export default USERS;
